[pytest]
testpaths = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --tb=short
    --strict-markers
    --disable-warnings
    --asyncio-mode=auto
;    --maxfail=1
    --hypothesis-show-statistics
markers =
    async: marks tests as async
    property: marks tests as property_based