"""Add is_featured flag

Revision ID: a2_featured
Revises: 08cc09f7fbe9
Create Date: 2026-07-18 06:05:04.717844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2_featured'
down_revision: Union[str, Sequence[str], None] = '08cc09f7fbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('is_featured', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.alter_column('product', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='product_status'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'status',
               existing_type=sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='product_status'),
               type_=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_column('product', 'is_featured')
    # ### end Alembic commands ###
